version: "3.9"

services:
  app:
    build: .
    ports:
      - 8080:8080
    container_name: sample_app
    environment:
      MYSQL_HOST: sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0.29
    container_name: sample_db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10